EMPTY = ""

class ClientType:
    NEW = "NEWCLIENT"
    EXISTING = "EXISTING_CLIENT"
    VOLUNTARY_HEALTH_INSURANCE = "VOLUNTARY_HEALTH_INSURANCE"
    CLIENT_TYPE_LIST = [NEW, EXISTING, VOLUNTARY_HEALTH_INSURANCE] 

class Sex:
    MALE = "Мужской"
    FEMALE = "Женский"
    SEX_LIST = [MALE, FEMALE]

class FirstName:
    INVALID_SPECIAL_SYMBOL = "VASYA-123 ВАСЯ!"
    VALID = "VASYA-123 ВАСЯ"

class SecondName:
    INVALID_SPECIAL_SYMBOL = "PUPKIN-123 ПУПКИН!"
    VALID = "PUPKIN-123 ПУПКИН"

class MiddleName:
    INVALID_SPECIAL_SYMBOL = "Petrovich-123 Петрович!"
    VALID = "Petrovich-123 Петрович"

class BDay:
    # negative
    INVALID_DAY_32="32012001"
    INVALID_DAY_0 = "00012001"
    INVALID_DAY_NEGATIVE = "-1012001"
    INVALID_DAY_POSITIVE = "+1012001"
    INVALID_DAY_DIES = "#1012001"
    INVALID_DAY_COMMA = ",1012001"
    INVALID_DAY_COMMA2 = "1,012001"
    INVALID_DAY_STAR = "1*012001"
    INVALID_DAY_N = "1N012001"
    INVALID_MONTH_13 = "30132001"
    INVALID_MONTH_0 = "30002001"
    INVALID_YEAR_1 = "30002"
    INVALID_YEAR_2 = "300020"
    INVALID_YEAR_3 = "3000200"
    INVALID_YEAR_5 = "300020000"
    INVALID_YEAR_EARLY = "31121899"
    INVALID_TOO_YOUNG = "31122020"
    INVALID_TOO_YOUNG_FOR_IOS = "1 марта 2015"
    INVALID_DATE_LIST = [EMPTY, INVALID_DAY_32,INVALID_DAY_0,INVALID_DAY_NEGATIVE,INVALID_DAY_POSITIVE,INVALID_DAY_DIES,
                         INVALID_DAY_COMMA,INVALID_DAY_COMMA2, INVALID_DAY_STAR, INVALID_DAY_N, INVALID_MONTH_13,
                         INVALID_MONTH_0, INVALID_YEAR_1, INVALID_YEAR_2, INVALID_YEAR_3, INVALID_YEAR_5,
                         INVALID_YEAR_EARLY]
    # positive
    VALID_FIRST_AVAILABLE_NUMBERS = "01011900"
    VALID_FIRST_AVAILABLE_WORDS = "1 января 1900 г."
    VALID_FIRST_AVAILABLE_WORDS_PRETTY = "01 января 1900"

class Email:
    # negative
    INVALID_NO_ADDRESS = "@bb.cc"
    INVALID_NO_2ND_LEVEL_DOMAIN = "aa@.cc"
    INVALID_NO_1ST_LEVEL_DOMAIN = "aa@.cc"
    INVALID_NO_AT = "aabb.cc"
    INVALID_NO_DOT = "aa@bbcc"
    INVALID_EMAIL_LIST = [INVALID_NO_ADDRESS, INVALID_NO_2ND_LEVEL_DOMAIN, INVALID_NO_2ND_LEVEL_DOMAIN, INVALID_NO_AT,
                          INVALID_NO_DOT]
    # positive
    VALID = "aa@bb.cc"

